# Задание 3 - Операции с матрицами в NumPy

## Картунчиков Артем ББМО-01-23

## Задание

1. Докажите, что транспонирование транспонированной матрицы - это сама матрица: $(\mathbf{A}^\top)^\top = \mathbf{A}$.
2. Для двух матриц $\mathbf{A}$ и $\mathbf{B}$, покажите, что сумма и транспозиция коммутируют: $\mathbf{A}^\top + \mathbf{B}^\top = (\mathbf{A} + \mathbf{B})^\top$.
3. Для любой квадратичной матрицы $\mathbf{A}$, сумма матриц $\mathbf{A} + \mathbf{A}^\top$ всегда ли симметрична? Можете ли вы доказать это, используя только предыдущие два упражнения?
4. Мы определяли тензор `X` размерности (2, 3, 4). Что возвращает функция `len(X)`? Попробуйте записать ответ используя воображение, потом проверьте свой ответ в среде программирования. 
5. Для тензора `X` произвольной размерности, всегда ли функция `len(X)` возвращает длину тензора по оси `X`? Что такое ось?
6. Запустите следующий фрагмент кода `A / A.sum(axis=1)` и проверьте полученный результат. Можете пояснить причину?
7. Рассмотрим тензор размерности (2, 3, 4). Какие размерности можно получить при суммирования элементов тензора по осям 0, 1 и 2?
9. Передайте тензор с 3 или более осями в функцию `linalg.norm` и наблюдайте за его выводом. Что эта функция вычисляет для тензоров произвольной формы?
10. Определите 3 матрицы $\mathbf{A} \in \mathbb{R}^{2^{10} \times 2^{16}}$, $\mathbf{B} \in \mathbb{R}^{2^{16} \times 2^{5}}$ и $\mathbf{C} \in \mathbb{R}^{2^{5} \times 2^{14}}$, содержащие случайные переменные, распределенные по нормальному закону распределения. Вычислите произведение матриц: $\mathbf{A} \mathbf{B} \mathbf{C}$. Есть ли какая-либо разница в объеме памяти и скорости в зависимости от того, вычилсяете Вы $(\mathbf{A} \mathbf{B}) \mathbf{C}$ или $\mathbf{A} (\mathbf{B} \mathbf{C})$. Объясните результаты?
11. Определите 3 матрицы $\mathbf{A} \in \mathbb{R}^{2^{10} \times 2^{16}}$, $\mathbf{B} \in \mathbb{R}^{2^{16} \times 2^{5}}$ and $\mathbf{C} \in \mathbb{R}^{2^{5} \times 2^{16}}$. Есть ли какая-либо разница в объеме памяти и скорости в зависимости от того, вычилсяете Вы $\mathbf{A} \mathbf{B}$ или $\mathbf{A} \mathbf{C}^\top$? Объясните результаты? Что изменится, если обозначить $\mathbf{C} = \mathbf{B}^\top$ без процедуры клонирования памяти? 
12. Определите 3 матрицы $\mathbf{A}, \mathbf{B}, \mathbf{C} \in \mathbb{R}^{100 \times 200}$. Сформируйте тензор с 3-мя осями путем объединения матриц $[\mathbf{A}, \mathbf{B}, \mathbf{C}]$. Какова размерность софрмирвоанного тензора? Вырежьте вторую координату третьей оси, чтобы восстановить $\mathbf{B}$. Проверьте, что ваш ответ правильный.


Импортируем нужные библиотеки

In [15]:
import numpy as np
import time



## 1. Докажите, что транспонирование транспонированной матрицы - это сама матрица: $(\mathbf{A}^\top)^\top = \mathbf{A}$.

In [5]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])


A_transpose_twice = A.T.T

print (A_transpose_twice)

are_equal = np.array_equal(A, A_transpose_twice)

if are_equal: 
    print("Матрицы равны")


[[1 2 3]
 [4 5 6]]
Матрицы равны


## 2. Для двух матриц $\mathbf{A}$ и $\mathbf{B}$, покажите, что сумма и транспозиция коммутируют: $\mathbf{A}^\top + \mathbf{B}^\top = (\mathbf{A} + \mathbf{B})^\top$.

In [6]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])


left_side = A.T + B.T
print(left_side)

right_side = (A + B).T
print(right_side)

are_equal = np.array_equal(left_side, right_side)
if are_equal:
    print("Матрицы равны")

[[ 6 10]
 [ 8 12]]
[[ 6 10]
 [ 8 12]]
Матрицы равны


## 3. Для любой квадратичной матрицы $\mathbf{A}$, сумма матриц $\mathbf{A} + \mathbf{A}^\top$ всегда ли симметрична? Можете ли вы доказать это, используя только предыдущие два упражнения?

In [7]:
A = np.random.randint(1, 10, size=(3, 3))

S = A + A.T
S_transposed = S.T

are_equal = np.array_equal(S, S_transposed)

if are_equal:
    print("Матрицы равны")

Матрицы равны


## 4. Мы определяли тензор `X` размерности (2, 3, 4). Что возвращает функция `len(X)`? Попробуйте записать ответ используя воображение, потом проверьте свой ответ в среде программирования. 

In [8]:
X = np.zeros((2, 3, 4))
print(len(X))

2


## 5. Для тензора `X` произвольной размерности, всегда ли функция `len(X)` возвращает длину тензора по оси `X`? Что такое ось?

In [11]:
print(len(np.random.rand(3, 5)))
print(len(np.random.rand(4, 2, 1)))
print(len(np.random.rand(74, 2, 4, 0)))

# Функция len(X) возвращает длину тензора только по его первой оси, то есть длину первого измерения.

# Ось в тензорах - это направление или измерение, вдоль которого происходят операции. В многомерных массивах, таких как тензоры, каждая ось представляет собой отдельное измерение данных.


3
4
74


## 6. Запустите следующий фрагмент кода `A / A.sum(axis=1)` и проверьте полученный результат. Можете пояснить причину?

Мы получили ошибку, так как при делении вторая строка матрицы A содержит нулевую сумму. Это приводит к попытке деления на ноль.

In [12]:
A = np.array([[1, 2, 3],
              [0, 0, 0]])

result = A / A.sum(axis=1)
print(result)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

## 7. Рассмотрим тензор размерности (2, 3, 4). Какие размерности можно получить при суммирования элементов тензора по осям 0, 1 и 2?

In [13]:

X = np.random.rand(2, 3, 4)


sum_axis_0 = X.sum(axis=0)
print(sum_axis_0.shape) 


sum_axis_1 = X.sum(axis=1)
print(sum_axis_1.shape)  


sum_axis_2 = X.sum(axis=2)
print(sum_axis_2.shape)  # Выводит размерность результата

(3, 4)
(2, 4)
(2, 3)


## 9. Передайте тензор с 3 или более осями в функцию `linalg.norm` и наблюдайте за его выводом. Что эта функция вычисляет для тензоров произвольной формы?


Функция linalg.norm используется для вычисления нормы (длины) вектора или матрицы. 

In [14]:
tensor = np.random.rand(3, 3, 3)

norm = np.linalg.norm(tensor)

print("Норма тензора:", norm)

Норма тензора: 2.777515268276199


## 10. Определите 3 матрицы $\mathbf{A} \in \mathbb{R}^{2^{10} \times 2^{16}}$, $\mathbf{B} \in \mathbb{R}^{2^{16} \times 2^{5}}$ и $\mathbf{C} \in \mathbb{R}^{2^{5} \times 2^{14}}$, содержащие случайные переменные, распределенные по нормальному закону распределения. Вычислите произведение матриц: $\mathbf{A} \mathbf{B} \mathbf{C}$. Есть ли какая-либо разница в объеме памяти и скорости в зависимости от того, вычилсяете Вы $(\mathbf{A} \mathbf{B}) \mathbf{C}$ или $\mathbf{A} (\mathbf{B} \mathbf{C})$. Объясните результаты?

По обычным правилам матричного умножения (AB)C и A(BC) должны давать одинаковые результаты. Однако может быть различие в скорости выполнения из-за различий в оптимизации вычислений библиотекой NumPy.

In [18]:
A_shape = (2**10, 2**16)
B_shape = (2**16, 2**5)
C_shape = (2**5, 2**14)

A = np.random.randn(*A_shape)
B = np.random.randn(*B_shape)
C = np.random.randn(*C_shape)

start_time = time.time()
result1 = np.dot(np.dot(A, B), C)
end_time = time.time()
time1 = end_time - start_time

start_time = time.time()
result2 = np.dot(A, np.dot(B, C))
end_time = time.time()
time2 = end_time - start_time


print("Время для (A * B * C):", time1)
print("Время для (A * (B * C)):", time2)

Время для (A * B * C): 0.09308409690856934
Время для (A * (B * C)): 11.575934648513794


## 11. Определите 3 матрицы $\mathbf{A} \in \mathbb{R}^{2^{10} \times 2^{16}}$, $\mathbf{B} \in \mathbb{R}^{2^{16} \times 2^{5}}$ and $\mathbf{C} \in \mathbb{R}^{2^{5} \times 2^{16}}$. Есть ли какая-либо разница в объеме памяти и скорости в зависимости от того, вычилсяете Вы $\mathbf{A} \mathbf{B}$ или $\mathbf{A} \mathbf{C}^\top$? Объясните результаты? Что изменится, если обозначить $\mathbf{C} = \mathbf{B}^\top$ без процедуры клонирования памяти? 

Eсли мы определим C=B^⊤ без процедуры клонирования памяти, то при создании переменной, которая ссылается на уже существующий массив, фактическое копирование памяти может произойти только тогда, когда переменная изменяется. 

In [20]:
C_shape = (2**5, 2**16)
C = np.random.randn(*C_shape)

start_time = time.time()
result_AB = np.dot(A, B)
end_time = time.time()
time_AB = end_time - start_time


start_time = time.time()
result_ACT = np.dot(A, C.T)
end_time = time.time()
time_ACT = end_time - start_time



print("Время для (A * B):", time_AB)

print("Время для (A * C^T):", time_ACT)

Время для (A * B): 0.057559967041015625
Время для (A * C^T): 0.05304861068725586


## 12. Определите 3 матрицы $\mathbf{A}, \mathbf{B}, \mathbf{C} \in \mathbb{R}^{100 \times 200}$. Сформируйте тензор с 3-мя осями путем объединения матриц $[\mathbf{A}, \mathbf{B}, \mathbf{C}]$. Какова размерность софрмирвоанного тензора? Вырежьте вторую координату третьей оси, чтобы восстановить $\mathbf{B}$. Проверьте, что ваш ответ правильный.


In [22]:

matrix_shape = (100, 200)


A = np.random.randn(*matrix_shape)
B = np.random.randn(*matrix_shape)
C = np.random.randn(*matrix_shape)


tensor = np.stack([A, B, C], axis=2)


print("Размерность тензора:", tensor.shape)


B_restored = tensor[:, :, 1]


print("Матрица B восстановлена успешно:", np.array_equal(B, B_restored))

Размерность тензора: (100, 200, 3)
Матрица B восстановлена успешно: True
